import 'multimodal/image_token_estimator.dart';

export 'multimodal/image_token_estimator.dart' show ImageDetail;

/// Role of a message in a chat conversation.
enum ChatRole {
  /// Instructions that shape the assistant's behaviour for the whole session.
  system,

  /// A message sent by the human participant.
  user,

  /// A message generated by the model.
  assistant,

  /// The result of a tool / function call.
  tool,
}

/// An image attachment that can be included in a [ChatMessage].
///
/// Pixel dimensions are used to calculate the token cost via
/// [ImageTokenEstimator] for each provider. If dimensions are unknown,
/// supply the provider-specific flat cost via [flatTokens] instead.
class ImageAttachment {
  /// Creates an image attachment.
  ///
  /// Either [width] + [height] must be provided, or [flatTokens] must be set.
  const ImageAttachment({
    this.width,
    this.height,
    this.detail = ImageDetail.auto,
    this.flatTokens,
  }) : assert(
         (width != null && height != null) || flatTokens != null,
         'Provide either width+height or flatTokens',
       );

  /// Actual image width in pixels.
  final int? width;

  /// Actual image height in pixels.
  final int? height;

  /// Detail level hint for OpenAI vision models.
  final ImageDetail detail;

  /// Override: use this fixed token count instead of the formula-based
  /// calculation. Useful when exact dimensions are unavailable.
  final int? flatTokens;

  @override
  String toString() =>
      'ImageAttachment(${width}x$height, detail: ${detail.name})';
}

/// A single message in a chat-style LLM call.
///
/// Chat APIs add per-message overhead (role tokens, separators). Use
/// [TokenCounter.countMessages] to include that overhead in the total.
///
/// To include images, pass them via [images]:
/// ```dart
/// ChatMessage.user(
///   'What is in this image?',
///   images: [ImageAttachment(width: 1024, height: 768)],
/// )
/// ```
class ChatMessage {
  /// Creates a chat message with the given [role] and [content].
  const ChatMessage({
    required this.role,
    required this.content,
    this.name,
    this.images = const [],
  });

  /// Creates a system message.
  const ChatMessage.system(String content)
    : this(role: ChatRole.system, content: content);

  /// Creates a user message, optionally with [images] attached.
  const ChatMessage.user(
    String content, {
    List<ImageAttachment> images = const [],
  }) : this(role: ChatRole.user, content: content, images: images);

  /// Creates an assistant message.
  const ChatMessage.assistant(String content)
    : this(role: ChatRole.assistant, content: content);

  /// Creates a tool-result message with an optional [name].
  const ChatMessage.tool(String content, {String? name})
    : this(role: ChatRole.tool, content: content, name: name);

  /// The role of the message sender.
  final ChatRole role;

  /// The text content of the message.
  final String content;

  /// Optional name identifier (used by some providers for tool results).
  final String? name;

  /// Images attached to this message (for vision models).
  final List<ImageAttachment> images;

  @override
  String toString() =>
      'ChatMessage(${role.name}: ${content.length} chars, '
      '${images.length} image(s))';
}
